name: Notes app cd pipeline

on:
  push:
    branches:
      - main
      - feature
      - feature/**
  pull_request:
    branches:
      - main

jobs:   
  terraform-apply:
    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: set ansible config secrets
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          #role-to-assume: arn:aws:iam::3198886108915:role/my-github-actions-role-test

        #   role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        #  role-duration-seconds: 1200
          #role-session-name: AssetsUploadSession
          
      - name: install make
        run: |
          sudo apt-get update
          sudo apt-get install make
      - name: make all_up
        run: make all-up
