name: Notes app cd pipeline

on:
  push:
    branches:
      - main
      - feature
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  Configure-AWS-Credentials:
    runs-on: ubuntu-latest
    steps: 
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install make
        run: |
          sudo apt-get update
          sudo apt-get install make
      - name: make all_up
        run: make all-up
