name: Notes app cd pipeline

on:
  push:
    branches:
      - main
      - feature
      - feature/**
  pull_request:
    branches:
      - main

jobs:        
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: generate key pairs
        run: yes '' | ssh-keygen -N '' > /dev/null
      - name: display key values
        run: cat ~/.ssh/id_rsa

      - name: setting-AWS-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: install make
        run: |
          sudo apt-get update
          sudo apt-get install make
          
      - name: make all-up
        run: make all-up
